/**
 * The editorial collections — ten shelves, seventy-two lists.
 *
 * A list here is an argument about what belongs next to what, so the unit of
 * data is the argument (title + description) and the titles are just its
 * evidence. Films are referenced by name rather than by slug because most of
 * them are not in the catalogue yet: scripts/seed-collections.ts resolves
 * each name against the catalogue first and pulls it from TMDB when it is
 * missing, which is why every entry carries a year and a kind.
 *
 * The year is not decoration. "Solaris", "Suspiria", "Scarface", "Cape Fear"
 * and "The Italian Job" all name two or more real films, and TMDB's search
 * ranks by popularity — so without a year the seeder would quietly stock the
 * remake. The kind separates the eight series here (Succession, Billions,
 * Peaky Blinders, House of Cards, Industry, Narcos, The Bear, Brideshead
 * Revisited) from the films, since a TMDB id only identifies a title
 * together with its type.
 */

export type SeedTitle = {
  /** The name the lists refer to, and the string searched on TMDB. */
  name: string;
  year: number;
  kind: "film" | "series";
  /**
   * A TMDB id, for the handful of titles a search cannot get right.
   *
   * Some names belong to a famous film and to an obscure one released the
   * same year, and the obscure one wins on an exact title-and-year match:
   * "The Witch" is Eggers in every conversation and also a Russian horror
   * film from 2015 with six votes, and "The Double" is Ayoade's and also a
   * Russian comedy from 2013. Pinning the id is the only fix that stays
   * fixed — the seeder skips the search entirely when this is set.
   */
  tmdbId?: number;
};

export type SeedList = {
  slug: string;
  title: string;
  description: string;
  /** Names from TITLES, in the order they should appear. */
  films: string[];
};

export type SeedCollection = {
  slug: string;
  name: string;
  lists: SeedList[];
};

export const TITLES: SeedTitle[] = [
  { name: "1917", year: 2019, kind: "film" },
  { name: "2001: A Space Odyssey", year: 1968, kind: "film" },
  { name: "8½", year: 1963, kind: "film" },
  { name: "A Beautiful Mind", year: 2001, kind: "film" },
  { name: "A Ghost Story", year: 2017, kind: "film" },
  { name: "A Prophet", year: 2009, kind: "film" },
  { name: "A Separation", year: 2011, kind: "film" },
  { name: "A.I. Artificial Intelligence", year: 2001, kind: "film" },
  { name: "About Time", year: 2013, kind: "film" },
  { name: "Ad Astra", year: 2019, kind: "film" },
  { name: "Adaptation.", year: 2002, kind: "film" },
  { name: "After Hours", year: 1985, kind: "film" },
  { name: "After Yang", year: 2021, kind: "film" },
  { name: "Aftersun", year: 2022, kind: "film" },
  { name: "All of Us Strangers", year: 2023, kind: "film" },
  { name: "All That Jazz", year: 1979, kind: "film" },
  { name: "All the President's Men", year: 1976, kind: "film" },
  { name: "Amadeus", year: 1984, kind: "film" },
  { name: "American Gangster", year: 2007, kind: "film" },
  { name: "American Psycho", year: 2000, kind: "film" },
  { name: "Amélie", year: 2001, kind: "film" },
  { name: "Anatomy of a Fall", year: 2023, kind: "film" },
  { name: "Aniara", year: 2018, kind: "film" },
  { name: "Annihilation", year: 2018, kind: "film" },
  { name: "Apocalypto", year: 2006, kind: "film" },
  { name: "Apollo 13", year: 1995, kind: "film" },
  { name: "Arbitrage", year: 2012, kind: "film" },
  { name: "Archive", year: 2020, kind: "film" },
  { name: "Arrival", year: 2016, kind: "film" },
  { name: "Audition", year: 1999, kind: "film" },
  { name: "Babylon", year: 2022, kind: "film" },
  { name: "Barry Lyndon", year: 1975, kind: "film" },
  { name: "Before Sunset", year: 2004, kind: "film" },
  { name: "Before the Devil Knows You're Dead", year: 2007, kind: "film" },
  { name: "Billions", year: 2016, kind: "series" },
  { name: "Birdman", year: 2014, kind: "film" },
  { name: "Black Swan", year: 2010, kind: "film" },
  { name: "Blade Runner", year: 1982, kind: "film" },
  { name: "Blade Runner 2049", year: 2017, kind: "film" },
  { name: "Blue Jay", year: 2016, kind: "film" },
  { name: "Blue Valentine", year: 2010, kind: "film" },
  { name: "Boiler Room", year: 2000, kind: "film" },
  { name: "Boiling Point", year: 2021, kind: "film" },
  { name: "Brideshead Revisited", year: 1981, kind: "series" },
  { name: "Brief Encounter", year: 1945, kind: "film" },
  { name: "Buried", year: 2010, kind: "film" },
  { name: "Burning", year: 2018, kind: "film" },
  { name: "Caché", year: 2005, kind: "film" },
  { name: "Cape Fear", year: 1991, kind: "film" },
  { name: "Carol", year: 2015, kind: "film" },
  { name: "Casino", year: 1995, kind: "film" },
  { name: "Catch Me If You Can", year: 2002, kind: "film" },
  { name: "Chef", year: 2014, kind: "film" },
  { name: "Chinatown", year: 1974, kind: "film" },
  { name: "Chungking Express", year: 1994, kind: "film" },
  { name: "City of God", year: 2002, kind: "film" },
  { name: "Climax", year: 2018, kind: "film" },
  { name: "Close Encounters of the Third Kind", year: 1977, kind: "film" },
  { name: "Closer", year: 2004, kind: "film" },
  { name: "CODA", year: 2021, kind: "film" },
  { name: "Coherence", year: 2013, kind: "film" },
  { name: "Cold War", year: 2018, kind: "film" },
  { name: "Collateral", year: 2004, kind: "film" },
  { name: "Columbus", year: 2017, kind: "film" },
  { name: "Come and See", year: 1985, kind: "film" },
  { name: "Contact", year: 1997, kind: "film" },
  { name: "Crank", year: 2006, kind: "film" },
  { name: "Cure", year: 1997, kind: "film" },
  { name: "Dark City", year: 1998, kind: "film" },
  { name: "Days of Heaven", year: 1978, kind: "film" },
  { name: "Decision to Leave", year: 2022, kind: "film" },
  { name: "District 9", year: 2009, kind: "film" },
  { name: "Dog Day Afternoon", year: 1975, kind: "film" },
  { name: "Donnie Brasco", year: 1997, kind: "film" },
  { name: "Donnie Darko", year: 2001, kind: "film" },
  { name: "Doubt", year: 2008, kind: "film" },
  { name: "Drive", year: 2011, kind: "film" },
  { name: "Drive My Car", year: 2021, kind: "film" },
  { name: "Dunkirk", year: 2017, kind: "film" },
  { name: "Eastern Promises", year: 2007, kind: "film" },
  { name: "Enemy", year: 2013, kind: "film" },
  { name: "Enter the Void", year: 2009, kind: "film" },
  { name: "Eternal Sunshine of the Spotless Mind", year: 2004, kind: "film" },
  { name: "Ex Machina", year: 2014, kind: "film" },
  { name: "eXistenZ", year: 1999, kind: "film" },
  { name: "Eyes Wide Shut", year: 1999, kind: "film" },
  { name: "Fallen Angels", year: 1995, kind: "film" },
  { name: "Falling Down", year: 1993, kind: "film" },
  { name: "Fight Club", year: 1999, kind: "film" },
  { name: "Ford v Ferrari", year: 2019, kind: "film" },
  { name: "Foxcatcher", year: 2014, kind: "film" },
  { name: "Funny Games", year: 1997, kind: "film" },
  { name: "Gattaca", year: 1997, kind: "film" },
  { name: "Gerry", year: 2002, kind: "film" },
  { name: "Get Out", year: 2017, kind: "film" },
  { name: "Ghost in the Shell", year: 1995, kind: "film" },
  { name: "Glass Onion", year: 2022, kind: "film" },
  { name: "Gomorrah", year: 2008, kind: "film" },
  { name: "Gone Girl", year: 2014, kind: "film" },
  { name: "Good Time", year: 2017, kind: "film" },
  { name: "Goodfellas", year: 1990, kind: "film" },
  { name: "Grave of the Fireflies", year: 1988, kind: "film" },
  { name: "Gravity", year: 2013, kind: "film" },
  { name: "Green Room", year: 2015, kind: "film" },
  { name: "Hard Boiled", year: 1992, kind: "film" },
  { name: "Heat", year: 1995, kind: "film" },
  { name: "Hell or High Water", year: 2016, kind: "film" },
  { name: "Henry: Portrait of a Serial Killer", year: 1986, kind: "film" },
  { name: "Her", year: 2013, kind: "film" },
  { name: "Hereditary", year: 2018, kind: "film" },
  { name: "Hero", year: 2002, kind: "film" },
  { name: "High Life", year: 2018, kind: "film" },
  { name: "High-Rise", year: 2015, kind: "film" },
  { name: "Hiroshima Mon Amour", year: 1959, kind: "film" },
  { name: "Holy Motors", year: 2012, kind: "film" },
  { name: "House of Cards", year: 2013, kind: "series" },
  { name: "I Am Mother", year: 2019, kind: "film" },
  { name: "In the Mood for Love", year: 2000, kind: "film" },
  { name: "Incendies", year: 2010, kind: "film" },
  { name: "Industry", year: 2020, kind: "series" },
  { name: "Infernal Affairs", year: 2002, kind: "film" },
  { name: "Inland Empire", year: 2006, kind: "film" },
  { name: "Inside Man", year: 2006, kind: "film" },
  { name: "Jacob's Ladder", year: 1990, kind: "film" },
  { name: "John Wick: Chapter 4", year: 2023, kind: "film" },
  { name: "Joy", year: 2015, kind: "film" },
  { name: "Julie & Julia", year: 2009, kind: "film" },
  { name: "Knives Out", year: 2019, kind: "film" },
  { name: "L.A. Confidential", year: 1997, kind: "film" },
  { name: "La La Land", year: 2016, kind: "film" },
  { name: "Last Year at Marienbad", year: 1961, kind: "film" },
  { name: "Le Samouraï", year: 1967, kind: "film" },
  { name: "Like Crazy", year: 2011, kind: "film" },
  { name: "Little Miss Sunshine", year: 2006, kind: "film" },
  { name: "Little Women", year: 2019, kind: "film" },
  { name: "Local Hero", year: 1983, kind: "film" },
  { name: "Logan Lucky", year: 2017, kind: "film" },
  { name: "Long Day's Journey Into Night", year: 2018, kind: "film" },
  { name: "Lost Highway", year: 1997, kind: "film" },
  { name: "Lost in Translation", year: 2003, kind: "film" },
  { name: "Mad Max: Fury Road", year: 2015, kind: "film" },
  { name: "Manchester by the Sea", year: 2016, kind: "film" },
  { name: "Mandy", year: 2018, kind: "film" },
  { name: "Margin Call", year: 2011, kind: "film" },
  { name: "Marriage Story", year: 2019, kind: "film" },
  { name: "Memento", year: 2000, kind: "film" },
  { name: "Memoria", year: 2021, kind: "film" },
  { name: "Memories of Murder", year: 2003, kind: "film" },
  { name: "Meshes of the Afternoon", year: 1943, kind: "film" },
  { name: "Metropolitan", year: 1990, kind: "film" },
  { name: "Michael Clayton", year: 2007, kind: "film" },
  { name: "Midnight in Paris", year: 2011, kind: "film" },
  { name: "Midsommar", year: 2019, kind: "film" },
  { name: "Millennium Mambo", year: 2001, kind: "film" },
  { name: "Miller's Crossing", year: 1990, kind: "film" },
  { name: "Minari", year: 2020, kind: "film" },
  { name: "Misery", year: 1990, kind: "film" },
  { name: "Mission: Impossible - Fallout", year: 2018, kind: "film" },
  { name: "Mon Oncle", year: 1958, kind: "film" },
  { name: "Moneyball", year: 2011, kind: "film" },
  { name: "Moon", year: 2009, kind: "film" },
  { name: "Moonlight", year: 2016, kind: "film" },
  { name: "Mother!", year: 2017, kind: "film" },
  { name: "Moulin Rouge!", year: 2001, kind: "film" },
  { name: "Mulholland Drive", year: 2001, kind: "film" },
  { name: "Mystic River", year: 2003, kind: "film" },
  { name: "Narcos", year: 2015, kind: "series" },
  { name: "Natural Born Killers", year: 1994, kind: "film" },
  { name: "Never Let Me Go", year: 2010, kind: "film" },
  { name: "Nightcrawler", year: 2014, kind: "film" },
  { name: "No Country for Old Men", year: 2007, kind: "film" },
  { name: "Nocturnal Animals", year: 2016, kind: "film" },
  { name: "Nomadland", year: 2020, kind: "film" },
  { name: "Ocean's Eleven", year: 2001, kind: "film" },
  { name: "Oldboy", year: 2003, kind: "film" },
  { name: "Once", year: 2007, kind: "film" },
  { name: "Once Upon a Time in America", year: 1984, kind: "film" },
  { name: "Oppenheimer", year: 2023, kind: "film" },
  { name: "Paddington 2", year: 2017, kind: "film" },
  { name: "Paprika", year: 2006, kind: "film" },
  { name: "Parasite", year: 2019, kind: "film" },
  { name: "Paris Texas", year: 1984, kind: "film" },
  { name: "Past Lives", year: 2023, kind: "film" },
  { name: "Paterson", year: 2016, kind: "film" },
  { name: "Peaky Blinders", year: 2013, kind: "series" },
  { name: "Perfect Blue", year: 1997, kind: "film" },
  { name: "Perfect Days", year: 2023, kind: "film" },
  { name: "Persona", year: 1966, kind: "film" },
  { name: "Phantom Thread", year: 2017, kind: "film" },
  { name: "Phone Booth", year: 2002, kind: "film" },
  { name: "Playtime", year: 1967, kind: "film" },
  { name: "Portrait of a Lady on Fire", year: 2019, kind: "film" },
  { name: "Possession", year: 1981, kind: "film" },
  { name: "Predestination", year: 2014, kind: "film" },
  { name: "Primal Fear", year: 1996, kind: "film" },
  { name: "Primer", year: 2004, kind: "film" },
  { name: "Prisoners", year: 2013, kind: "film" },
  { name: "Ready or Not", year: 2019, kind: "film" },
  { name: "Repulsion", year: 1965, kind: "film" },
  { name: "Requiem for a Dream", year: 2000, kind: "film" },
  { name: "Reservoir Dogs", year: 1992, kind: "film" },
  { name: "Revolutionary Road", year: 2008, kind: "film" },
  { name: "Rififi", year: 1955, kind: "film" },
  { name: "Road to Perdition", year: 2002, kind: "film" },
  { name: "Rosemary's Baby", year: 1968, kind: "film" },
  { name: "Run Lola Run", year: 1998, kind: "film" },
  { name: "Saint Maud", year: 2019, kind: "film" },
  { name: "Saltburn", year: 2023, kind: "film" },
  { name: "Scarface", year: 1983, kind: "film" },
  { name: "Scenes from a Marriage", year: 1974, kind: "film" },
  { name: "Seconds", year: 1966, kind: "film" },
  { name: "Serpico", year: 1973, kind: "film" },
  { name: "Sexy Beast", year: 2000, kind: "film" },
  { name: "Shiva Baby", year: 2020, kind: "film" },
  { name: "Shutter Island", year: 2010, kind: "film" },
  { name: "Sicario", year: 2015, kind: "film" },
  { name: "Silent Running", year: 1972, kind: "film" },
  { name: "Sing Street", year: 2016, kind: "film" },
  { name: "Sleuth", year: 1972, kind: "film" },
  { name: "Snowpiercer", year: 2013, kind: "film" },
  { name: "Solaris", year: 1972, kind: "film" },
  { name: "Sorcerer", year: 1977, kind: "film" },
  { name: "Source Code", year: 2011, kind: "film" },
  { name: "Speak No Evil", year: 2022, kind: "film" },
  { name: "Speed", year: 1994, kind: "film" },
  { name: "Spotlight", year: 2015, kind: "film" },
  { name: "Spring Breakers", year: 2012, kind: "film" },
  { name: "Stalker", year: 1979, kind: "film" },
  { name: "Steve Jobs", year: 2015, kind: "film" },
  { name: "Still Walking", year: 2008, kind: "film" },
  { name: "Succession", year: 2018, kind: "series" },
  { name: "Suspiria", year: 1977, kind: "film" },
  { name: "Synecdoche New York", year: 2008, kind: "film" },
  { name: "Take Shelter", year: 2011, kind: "film" },
  { name: "Taste of Cherry", year: 1997, kind: "film" },
  { name: "The Accountant", year: 2016, kind: "film" },
  { name: "The Apprentice", year: 2024, kind: "film" },
  { name: "The Assassination of Jesse James by the Coward Robert Ford", year: 2007, kind: "film" },
  { name: "The Assistant", year: 2019, kind: "film" },
  { name: "The Autopsy of Jane Doe", year: 2016, kind: "film" },
  { name: "The Bear", year: 2022, kind: "series" },
  { name: "The Big Short", year: 2015, kind: "film" },
  { name: "The Blackcoat's Daughter", year: 2015, kind: "film" },
  { name: "The Brutalist", year: 2024, kind: "film" },
  { name: "The Conformist", year: 1970, kind: "film" },
  { name: "The Conjuring", year: 2013, kind: "film" },
  { name: "The Cook the Thief His Wife & Her Lover", year: 1989, kind: "film" },
  { name: "The Creator", year: 2023, kind: "film" },
  { name: "The Dark and the Wicked", year: 2020, kind: "film" },
  { name: "The Day the Earth Stood Still", year: 1951, kind: "film" },
  { name: "The Departed", year: 2006, kind: "film" },
  { name: "The Devil Wears Prada", year: 2006, kind: "film" },
  { name: "The Discreet Charm of the Bourgeoisie", year: 1972, kind: "film" },
  { name: "The Double", year: 2014, kind: "film", tmdbId: 146015 },
  { name: "The Double Life of Véronique", year: 1991, kind: "film" },
  { name: "The Exorcist", year: 1973, kind: "film" },
  { name: "The Fall", year: 2006, kind: "film" },
  { name: "The Farewell", year: 2019, kind: "film" },
  { name: "The Favourite", year: 2018, kind: "film" },
  { name: "The Founder", year: 2016, kind: "film" },
  { name: "The Game", year: 1997, kind: "film" },
  { name: "The Gentlemen", year: 2020, kind: "film" },
  { name: "The Gift", year: 2015, kind: "film" },
  { name: "The Godfather", year: 1972, kind: "film" },
  { name: "The Godfather Part II", year: 1974, kind: "film" },
  { name: "The Grand Budapest Hotel", year: 2014, kind: "film" },
  { name: "The Great Gatsby", year: 2013, kind: "film" },
  { name: "The Grudge", year: 2004, kind: "film" },
  { name: "The Guilty", year: 2018, kind: "film" },
  { name: "The Handmaiden", year: 2016, kind: "film" },
  { name: "The Holdovers", year: 2023, kind: "film" },
  { name: "The Hunt", year: 2012, kind: "film" },
  { name: "The Imitation Game", year: 2014, kind: "film" },
  { name: "The Insider", year: 1999, kind: "film" },
  { name: "The Intern", year: 2015, kind: "film" },
  { name: "The Intouchables", year: 2011, kind: "film" },
  { name: "The Invitation", year: 2016, kind: "film" },
  { name: "The Irishman", year: 2019, kind: "film" },
  { name: "The Italian Job", year: 1969, kind: "film" },
  { name: "The Killing", year: 1956, kind: "film" },
  { name: "The Killing of a Sacred Deer", year: 2017, kind: "film" },
  { name: "The King of Comedy", year: 1982, kind: "film" },
  { name: "The Leopard", year: 1963, kind: "film" },
  { name: "The Lighthouse", year: 2019, kind: "film" },
  { name: "The Lives of Others", year: 2006, kind: "film" },
  { name: "The Lunchbox", year: 2013, kind: "film" },
  { name: "The Machinist", year: 2004, kind: "film" },
  { name: "The Martian", year: 2015, kind: "film" },
  { name: "The Matrix", year: 1999, kind: "film" },
  { name: "The Menu", year: 2022, kind: "film" },
  { name: "The Neon Demon", year: 2016, kind: "film" },
  { name: "The Nice Guys", year: 2016, kind: "film" },
  { name: "The Novice", year: 2021, kind: "film" },
  { name: "The Others", year: 2001, kind: "film" },
  { name: "The Peanut Butter Falcon", year: 2019, kind: "film" },
  { name: "The Prestige", year: 2006, kind: "film" },
  { name: "The Pursuit of Happyness", year: 2006, kind: "film" },
  { name: "The Raid", year: 2011, kind: "film" },
  { name: "The Red Shoes", year: 1948, kind: "film" },
  { name: "The Remains of the Day", year: 1993, kind: "film" },
  { name: "The Ring", year: 2002, kind: "film" },
  { name: "The Score", year: 2001, kind: "film" },
  { name: "The Secret in Their Eyes", year: 2009, kind: "film" },
  { name: "The Secret Life of Walter Mitty", year: 2013, kind: "film" },
  { name: "The Shining", year: 1980, kind: "film" },
  { name: "The Silence of the Lambs", year: 1991, kind: "film" },
  { name: "The Sixth Sense", year: 1999, kind: "film" },
  { name: "The Skin I Live In", year: 2011, kind: "film" },
  { name: "The Social Network", year: 2010, kind: "film" },
  { name: "The Station Agent", year: 2003, kind: "film" },
  { name: "The Stepford Wives", year: 1975, kind: "film" },
  { name: "The Straight Story", year: 1999, kind: "film" },
  { name: "The Talented Mr. Ripley", year: 1999, kind: "film" },
  { name: "The Thirteenth Floor", year: 1999, kind: "film" },
  { name: "The Town", year: 2010, kind: "film" },
  { name: "The Turin Horse", year: 2011, kind: "film" },
  { name: "The Umbrellas of Cherbourg", year: 1964, kind: "film" },
  { name: "The Vanishing", year: 1988, kind: "film" },
  { name: "The Vast of Night", year: 2019, kind: "film" },
  { name: "The Wailing", year: 2016, kind: "film" },
  { name: "The White Ribbon", year: 2009, kind: "film" },
  { name: "The Witch", year: 2016, kind: "film", tmdbId: 310131 },
  { name: "The Wolf of Wall Street", year: 2013, kind: "film" },
  { name: "The Worst Person in the World", year: 2021, kind: "film" },
  { name: "The Zone of Interest", year: 2023, kind: "film" },
  { name: "There Will Be Blood", year: 2007, kind: "film" },
  { name: "Thief", year: 1981, kind: "film" },
  { name: "Three Colours: Blue", year: 1993, kind: "film" },
  { name: "Tinker Tailor Soldier Spy", year: 2011, kind: "film" },
  { name: "Train to Busan", year: 2016, kind: "film" },
  { name: "Training Day", year: 2001, kind: "film" },
  { name: "Triangle of Sadness", year: 2022, kind: "film" },
  { name: "Tár", year: 2022, kind: "film" },
  { name: "Uncle Boonmee Who Can Recall His Past Lives", year: 2010, kind: "film" },
  { name: "Uncut Gems", year: 2019, kind: "film" },
  { name: "Under the Skin", year: 2013, kind: "film" },
  { name: "Up in the Air", year: 2009, kind: "film" },
  { name: "Upgrade", year: 2018, kind: "film" },
  { name: "Vertigo", year: 1958, kind: "film" },
  { name: "Victoria", year: 2015, kind: "film" },
  { name: "Wall Street", year: 1987, kind: "film" },
  { name: "Werckmeister Harmonies", year: 2000, kind: "film" },
  { name: "Whiplash", year: 2014, kind: "film" },
  { name: "Zodiac", year: 2007, kind: "film" },
];

export const COLLECTIONS: SeedCollection[] = [
  {
    slug: "power-wealth-ambition",
    name: "Power, wealth & ambition",
    lists: [
      {
        slug: "power-plays",
        title: "Power Plays",
        description: "Status, leverage and manipulation",
        films: [
          "Succession",
          "Billions",
          "Peaky Blinders",
          "House of Cards",
          "The Godfather",
          "There Will Be Blood",
          "The Favourite",
          "The Apprentice",
        ],
      },
      {
        slug: "money-is-the-weapon",
        title: "Money Is the Weapon",
        description: "Wealth used as leverage and control",
        films: [
          "Billions",
          "Wall Street",
          "Margin Call",
          "The Big Short",
          "Industry",
          "Arbitrage",
          "Boiler Room",
          "The Wolf of Wall Street",
        ],
      },
      {
        slug: "built-from-nothing",
        title: "Built From Nothing",
        description: "Ambitious outsiders rising to power",
        films: [
          "Scarface",
          "Peaky Blinders",
          "The Social Network",
          "There Will Be Blood",
          "The Founder",
          "American Gangster",
          "The Pursuit of Happyness",
          "Joy",
        ],
      },
      {
        slug: "boardroom-bloodsport",
        title: "Boardroom Bloodsport",
        description: "Corporate life as warfare",
        films: [
          "Succession",
          "Billions",
          "Industry",
          "Margin Call",
          "Michael Clayton",
          "The Insider",
          "The Apprentice",
          "Wall Street",
        ],
      },
      {
        slug: "masters-of-the-game",
        title: "Masters of the Game",
        description: "People always thinking several moves ahead",
        films: [
          "The Godfather",
          "Peaky Blinders",
          "House of Cards",
          "The Prestige",
          "The Departed",
          "Tinker Tailor Soldier Spy",
          "Inside Man",
          "Infernal Affairs",
        ],
      },
      {
        slug: "the-price-of-ambition",
        title: "The Price of Ambition",
        description: "Achievement that consumes the person pursuing it",
        films: [
          "Whiplash",
          "Black Swan",
          "There Will Be Blood",
          "Nightcrawler",
          "The Social Network",
          "Tár",
          "The Prestige",
          "Birdman",
        ],
      },
      {
        slug: "old-money-new-money",
        title: "Old Money New Money",
        description: "Wealth, inheritance and social hierarchy",
        films: [
          "Succession",
          "Saltburn",
          "The Great Gatsby",
          "The Talented Mr. Ripley",
          "The Favourite",
          "The Leopard",
          "Metropolitan",
          "Brideshead Revisited",
        ],
      },
      {
        slug: "eat-the-rich",
        title: "Eat the Rich",
        description: "Class resentment and satire of privilege",
        films: [
          "Parasite",
          "Triangle of Sadness",
          "The Menu",
          "Saltburn",
          "Ready or Not",
          "Snowpiercer",
          "High-Rise",
          "Glass Onion",
        ],
      },
    ],
  },
  {
    slug: "crime",
    name: "Crime",
    lists: [
      {
        slug: "beautiful-crime",
        title: "Beautiful Crime",
        description: "Crime with exceptional visual style",
        films: [
          "Heat",
          "Drive",
          "Peaky Blinders",
          "The Godfather",
          "Thief",
          "Collateral",
          "The Assassination of Jesse James by the Coward Robert Ford",
          "Le Samouraï",
        ],
      },
      {
        slug: "crime-is-a-business",
        title: "Crime Is a Business",
        description: "Criminal organizations operating like corporations",
        films: [
          "The Godfather",
          "Goodfellas",
          "Peaky Blinders",
          "Casino",
          "American Gangster",
          "Narcos",
          "Gomorrah",
          "The Irishman",
        ],
      },
      {
        slug: "kings-of-the-underworld",
        title: "Kings of the Underworld",
        description: "Building and controlling criminal empires",
        films: [
          "Scarface",
          "The Godfather Part II",
          "Casino",
          "American Gangster",
          "Once Upon a Time in America",
          "City of God",
          "Eastern Promises",
          "Peaky Blinders",
        ],
      },
      {
        slug: "one-last-job",
        title: "One Last Job",
        description: "Criminals attempting the final score",
        films: [
          "Heat",
          "The Town",
          "Thief",
          "Sexy Beast",
          "Logan Lucky",
          "The Score",
          "Hell or High Water",
          "Rififi",
        ],
      },
      {
        slug: "perfect-heists",
        title: "Perfect Heists",
        description: "Planning, precision and execution",
        films: [
          "Ocean's Eleven",
          "Inside Man",
          "Rififi",
          "The Town",
          "Heat",
          "The Italian Job",
          "Logan Lucky",
          "The Killing",
        ],
      },
      {
        slug: "bad-men-in-good-suits",
        title: "Bad Men in Good Suits",
        description: "Elegant people doing terrible things",
        films: [
          "The Godfather",
          "Peaky Blinders",
          "The Gentlemen",
          "Eastern Promises",
          "Casino",
          "Reservoir Dogs",
          "The Irishman",
          "Road to Perdition",
        ],
      },
      {
        slug: "loyalty-has-a-price",
        title: "Loyalty Has a Price",
        description: "Friendship, family and betrayal in criminal worlds",
        films: [
          "Goodfellas",
          "Donnie Brasco",
          "The Departed",
          "A Prophet",
          "Infernal Affairs",
          "The Irishman",
          "Miller's Crossing",
          "The Godfather Part II",
        ],
      },
      {
        slug: "cops-and-criminals",
        title: "Cops and Criminals",
        description: "Hunters and hunted increasingly resemble each other",
        films: [
          "Heat",
          "The Departed",
          "Infernal Affairs",
          "Sicario",
          "Training Day",
          "Memories of Murder",
          "L.A. Confidential",
          "Serpico",
        ],
      },
    ],
  },
  {
    slug: "psychological",
    name: "Psychological",
    lists: [
      {
        slug: "mind-games",
        title: "Mind Games",
        description: "Psychological and intellectual conflict",
        films: [
          "Gone Girl",
          "The Prestige",
          "The Game",
          "Oldboy",
          "Ex Machina",
          "The Handmaiden",
          "Primal Fear",
          "Sleuth",
        ],
      },
      {
        slug: "nothing-is-what-it-seems",
        title: "Nothing Is What It Seems",
        description: "Reality gradually stops making sense",
        films: [
          "Shutter Island",
          "Mulholland Drive",
          "Fight Club",
          "The Sixth Sense",
          "The Others",
          "Enemy",
          "Coherence",
          "Predestination",
        ],
      },
      {
        slug: "unreliable-minds",
        title: "Unreliable Minds",
        description: "You cannot completely trust the protagonist’s reality",
        films: [
          "Memento",
          "Black Swan",
          "The Machinist",
          "Fight Club",
          "Perfect Blue",
          "Shutter Island",
          "Jacob's Ladder",
          "American Psycho",
        ],
      },
      {
        slug: "slowly-losing-it",
        title: "Slowly Losing It",
        description: "Gradual psychological deterioration",
        films: [
          "The Shining",
          "Black Swan",
          "The Lighthouse",
          "Repulsion",
          "The Machinist",
          "Saint Maud",
          "Possession",
          "Take Shelter",
        ],
      },
      {
        slug: "obsession-takes-over",
        title: "Obsession Takes Over",
        description: "Fixation consumes everything else",
        films: [
          "Vertigo",
          "Zodiac",
          "The Prestige",
          "Whiplash",
          "Black Swan",
          "Nightcrawler",
          "Phantom Thread",
          "The King of Comedy",
        ],
      },
      {
        slug: "morally-complicated",
        title: "Morally Complicated",
        description: "Films that refuse simple heroes and villains",
        films: [
          "Prisoners",
          "A Separation",
          "Burning",
          "Decision to Leave",
          "Anatomy of a Fall",
          "Incendies",
          "The Hunt",
          "Doubt",
        ],
      },
      {
        slug: "identity-crisis",
        title: "Identity Crisis",
        description: "Characters become uncertain about who they are",
        films: [
          "Persona",
          "Fight Club",
          "Perfect Blue",
          "Enemy",
          "Mulholland Drive",
          "Lost Highway",
          "Seconds",
          "The Double",
        ],
      },
      {
        slug: "the-truth-will-hurt",
        title: "The Truth Will Hurt",
        description: "Discovering the answer makes everything worse",
        films: [
          "Incendies",
          "Oldboy",
          "Prisoners",
          "The Secret in Their Eyes",
          "Chinatown",
          "Mystic River",
          "The Vanishing",
          "The Lives of Others",
        ],
      },
    ],
  },
  {
    slug: "dark-unsettling",
    name: "Dark & unsettling",
    lists: [
      {
        slug: "quiet-dread",
        title: "Quiet Dread",
        description: "Slow tension without conventional horror",
        films: [
          "Burning",
          "The Zone of Interest",
          "Caché",
          "Cure",
          "The Killing of a Sacred Deer",
          "The Vanishing",
          "Nocturnal Animals",
          "The White Ribbon",
        ],
      },
      {
        slug: "something-is-wrong-here",
        title: "Something Is Wrong Here",
        description: "Everything appears normal—until it doesn’t",
        films: [
          "Get Out",
          "Rosemary's Baby",
          "The Invitation",
          "The Killing of a Sacred Deer",
          "The Stepford Wives",
          "Speak No Evil",
          "The Gift",
          "Cure",
        ],
      },
      {
        slug: "slow-burn-nightmares",
        title: "Slow-Burn Nightmares",
        description: "Patient stories gradually becoming horrifying",
        films: [
          "The Witch",
          "Cure",
          "Burning",
          "Hereditary",
          "Saint Maud",
          "The Wailing",
          "The Blackcoat's Daughter",
          "Audition",
        ],
      },
      {
        slug: "no-way-out",
        title: "No Way Out",
        description: "Characters trapped by increasingly impossible circumstances",
        films: [
          "Good Time",
          "Green Room",
          "Uncut Gems",
          "Buried",
          "Dog Day Afternoon",
          "Victoria",
          "After Hours",
          "The Guilty",
        ],
      },
      {
        slug: "anxiety-for-two-hours",
        title: "Anxiety for Two Hours",
        description: "Relentless cinematic stress",
        films: [
          "Uncut Gems",
          "Good Time",
          "Sicario",
          "Whiplash",
          "Victoria",
          "Shiva Baby",
          "Sorcerer",
          "Boiling Point",
        ],
      },
      {
        slug: "human-monsters",
        title: "Human Monsters",
        description: "The frightening thing is another person",
        films: [
          "The Vanishing",
          "Nightcrawler",
          "Funny Games",
          "The Silence of the Lambs",
          "Henry: Portrait of a Serial Killer",
          "No Country for Old Men",
          "Misery",
          "Cape Fear",
        ],
      },
      {
        slug: "beautifully-disturbing",
        title: "Beautifully Disturbing",
        description: "Gorgeous filmmaking paired with disturbing subject matter",
        films: [
          "Midsommar",
          "The Neon Demon",
          "The Skin I Live In",
          "Eyes Wide Shut",
          "The Handmaiden",
          "Climax",
          "Under the Skin",
          "Possession",
        ],
      },
      {
        slug: "don-t-watch-alone",
        title: "Don’t Watch Alone",
        description: "Cinema designed to genuinely frighten",
        films: [
          "Hereditary",
          "The Exorcist",
          "The Conjuring",
          "The Ring",
          "The Wailing",
          "The Dark and the Wicked",
          "The Autopsy of Jane Doe",
          "The Grudge",
        ],
      },
    ],
  },
  {
    slug: "visual-atmospheric",
    name: "Visual & atmospheric",
    lists: [
      {
        slug: "neon-loneliness",
        title: "Neon Loneliness",
        description: "Urban isolation under artificial light",
        films: [
          "Fallen Angels",
          "Drive",
          "Lost in Translation",
          "Chungking Express",
          "Blade Runner 2049",
          "Her",
          "Millennium Mambo",
          "Collateral",
        ],
      },
      {
        slug: "every-frame-a-painting",
        title: "Every Frame a Painting",
        description: "Extraordinary visual composition",
        films: [
          "In the Mood for Love",
          "Barry Lyndon",
          "The Grand Budapest Hotel",
          "The Fall",
          "Hero",
          "The Assassination of Jesse James by the Coward Robert Ford",
          "Days of Heaven",
          "The Conformist",
        ],
      },
      {
        slug: "dream-logic",
        title: "Dream Logic",
        description: "Films that operate according to dreams rather than conventional reality",
        films: [
          "Mulholland Drive",
          "Paprika",
          "8½",
          "Persona",
          "The Discreet Charm of the Bourgeoisie",
          "Last Year at Marienbad",
          "Meshes of the Afternoon",
          "Holy Motors",
        ],
      },
      {
        slug: "cities-after-dark",
        title: "Cities After Dark",
        description: "The city transforms after sunset",
        films: [
          "Collateral",
          "Fallen Angels",
          "After Hours",
          "Drive",
          "Victoria",
          "Nightcrawler",
          "Good Time",
          "Thief",
        ],
      },
      {
        slug: "beautiful-emptiness",
        title: "Beautiful Emptiness",
        description: "Space, silence and solitude",
        films: [
          "Paris Texas",
          "Perfect Days",
          "Columbus",
          "Nomadland",
          "The Straight Story",
          "Taste of Cherry",
          "Gerry",
          "Paterson",
        ],
      },
      {
        slug: "colour-is-the-story",
        title: "Colour Is the Story",
        description: "Colour functioning as part of the storytelling",
        films: [
          "In the Mood for Love",
          "Hero",
          "Suspiria",
          "The Double Life of Véronique",
          "Three Colours: Blue",
          "The Cook the Thief His Wife & Her Lover",
          "Moonlight",
          "The Umbrellas of Cherbourg",
        ],
      },
      {
        slug: "architecture-as-character",
        title: "Architecture as Character",
        description: "Buildings and spaces become part of the narrative",
        films: [
          "The Brutalist",
          "Columbus",
          "Playtime",
          "Parasite",
          "Blade Runner 2049",
          "The Shining",
          "High-Rise",
          "Mon Oncle",
        ],
      },
      {
        slug: "hypnotic-cinema",
        title: "Hypnotic Cinema",
        description: "Slow, immersive, almost trance-like cinema",
        films: [
          "Stalker",
          "Long Day's Journey Into Night",
          "Uncle Boonmee Who Can Recall His Past Lives",
          "Memoria",
          "Solaris",
          "Werckmeister Harmonies",
          "The Turin Horse",
          "Inland Empire",
        ],
      },
    ],
  },
  {
    slug: "love-emotion",
    name: "Love & emotion",
    lists: [
      {
        slug: "beautifully-miserable",
        title: "Beautifully Miserable",
        description: "Beautiful films that emotionally destroy you",
        films: [
          "Aftersun",
          "In the Mood for Love",
          "Blue Valentine",
          "Manchester by the Sea",
          "Portrait of a Lady on Fire",
          "All of Us Strangers",
          "Never Let Me Go",
          "The Worst Person in the World",
        ],
      },
      {
        slug: "right-person-wrong-time",
        title: "Right Person Wrong Time",
        description: "Love defeated by circumstance or timing",
        films: [
          "Past Lives",
          "La La Land",
          "In the Mood for Love",
          "Brief Encounter",
          "The Umbrellas of Cherbourg",
          "Once",
          "Like Crazy",
          "The Remains of the Day",
        ],
      },
      {
        slug: "love-without-saying-it",
        title: "Love Without Saying It",
        description: "Romance expressed through gestures and silence",
        films: [
          "Portrait of a Lady on Fire",
          "Past Lives",
          "Brief Encounter",
          "In the Mood for Love",
          "Carol",
          "Phantom Thread",
          "Decision to Leave",
          "The Remains of the Day",
        ],
      },
      {
        slug: "almost-lovers",
        title: "Almost Lovers",
        description: "Relationships suspended between friendship and romance",
        films: [
          "Lost in Translation",
          "Past Lives",
          "In the Mood for Love",
          "Once",
          "Before Sunset",
          "Her",
          "Decision to Leave",
          "The Lunchbox",
        ],
      },
      {
        slug: "love-hurts",
        title: "Love Hurts",
        description: "Relationships become painful or destructive",
        films: [
          "Blue Valentine",
          "Marriage Story",
          "Revolutionary Road",
          "Closer",
          "Scenes from a Marriage",
          "Cold War",
          "The Worst Person in the World",
          "Eternal Sunshine of the Spotless Mind",
        ],
      },
      {
        slug: "quietly-heartbreaking",
        title: "Quietly Heartbreaking",
        description: "Emotional devastation without conventional melodrama",
        films: [
          "Aftersun",
          "Manchester by the Sea",
          "Past Lives",
          "Never Let Me Go",
          "The Remains of the Day",
          "Still Walking",
          "Drive My Car",
          "A Ghost Story",
        ],
      },
      {
        slug: "i-need-a-minute",
        title: "I Need a Minute",
        description: "Films that leave you sitting through the credits",
        films: [
          "Aftersun",
          "Incendies",
          "Grave of the Fireflies",
          "Come and See",
          "The Hunt",
          "Manchester by the Sea",
          "Requiem for a Dream",
          "All of Us Strangers",
        ],
      },
      {
        slug: "memory-of-love",
        title: "Memory of Love",
        description: "Romance remembered rather than simply experienced",
        films: [
          "Past Lives",
          "In the Mood for Love",
          "Eternal Sunshine of the Spotless Mind",
          "Aftersun",
          "Blue Jay",
          "Cold War",
          "Hiroshima Mon Amour",
          "The Worst Person in the World",
        ],
      },
    ],
  },
  {
    slug: "obsession-intelligence-work",
    name: "Obsession, intelligence & work",
    lists: [
      {
        slug: "professional-obsession",
        title: "Professional Obsession",
        description: "Excellence becomes destructive",
        films: [
          "Whiplash",
          "Black Swan",
          "Tár",
          "The Prestige",
          "Phantom Thread",
          "Nightcrawler",
          "The Novice",
          "Foxcatcher",
        ],
      },
      {
        slug: "competence-is-attractive",
        title: "Competence Is Attractive",
        description: "Watching extremely capable people work",
        films: [
          "Michael Clayton",
          "The Martian",
          "Spotlight",
          "Moneyball",
          "Thief",
          "Apollo 13",
          "Ford v Ferrari",
          "The Accountant",
        ],
      },
      {
        slug: "genius-has-a-cost",
        title: "Genius Has a Cost",
        description: "Exceptional ability paired with personal consequences",
        films: [
          "Oppenheimer",
          "Amadeus",
          "The Imitation Game",
          "A Beautiful Mind",
          "Steve Jobs",
          "The Social Network",
          "Tár",
          "Whiplash",
        ],
      },
      {
        slug: "work-is-my-personality",
        title: "Work Is My Personality",
        description: "Career consumes identity",
        films: [
          "The Devil Wears Prada",
          "Tár",
          "Whiplash",
          "Michael Clayton",
          "Up in the Air",
          "Nightcrawler",
          "Black Swan",
          "The Assistant",
        ],
      },
      {
        slug: "systems-and-strategy",
        title: "Systems and Strategy",
        description: "Smart people understanding complicated systems",
        films: [
          "Moneyball",
          "Margin Call",
          "The Big Short",
          "Spotlight",
          "The Social Network",
          "All the President's Men",
          "The Insider",
          "Tinker Tailor Soldier Spy",
        ],
      },
      {
        slug: "creative-obsession",
        title: "Creative Obsession",
        description: "Artists consumed by the need to create",
        films: [
          "Black Swan",
          "Birdman",
          "Synecdoche New York",
          "8½",
          "Amadeus",
          "Adaptation.",
          "The Red Shoes",
          "All That Jazz",
        ],
      },
    ],
  },
  {
    slug: "chaos-adrenaline",
    name: "Chaos & adrenaline",
    lists: [
      {
        slug: "everything-is-falling-apart",
        title: "Everything Is Falling Apart",
        description: "Controlled chaos escalating constantly",
        films: [
          "Uncut Gems",
          "Good Time",
          "Shiva Baby",
          "After Hours",
          "Boiling Point",
          "Victoria",
          "The Bear",
          "Mother!",
        ],
      },
      {
        slug: "one-very-bad-day",
        title: "One Very Bad Day",
        description: "A single day spirals completely out of control",
        films: [
          "After Hours",
          "Good Time",
          "Dog Day Afternoon",
          "Falling Down",
          "Training Day",
          "Collateral",
          "Victoria",
          "Before the Devil Knows You're Dead",
        ],
      },
      {
        slug: "can-t-look-away",
        title: "Can’t Look Away",
        description: "Relentless momentum",
        films: [
          "Mad Max: Fury Road",
          "Whiplash",
          "Uncut Gems",
          "Good Time",
          "The Raid",
          "Apocalypto",
          "Run Lola Run",
          "Train to Busan",
        ],
      },
      {
        slug: "beautiful-chaos",
        title: "Beautiful Chaos",
        description: "Disorder presented with visual bravado",
        films: [
          "Babylon",
          "Climax",
          "Spring Breakers",
          "Moulin Rouge!",
          "Natural Born Killers",
          "Enter the Void",
          "Good Time",
          "Mandy",
        ],
      },
      {
        slug: "race-against-time",
        title: "Race Against Time",
        description: "The clock is part of the antagonist",
        films: [
          "Dunkirk",
          "Run Lola Run",
          "Speed",
          "1917",
          "Victoria",
          "Good Time",
          "Source Code",
          "Phone Booth",
        ],
      },
      {
        slug: "adrenaline-cinema",
        title: "Adrenaline Cinema",
        description: "Pure kinetic filmmaking",
        films: [
          "Mad Max: Fury Road",
          "The Raid",
          "Mission: Impossible - Fallout",
          "John Wick: Chapter 4",
          "Train to Busan",
          "Apocalypto",
          "Crank",
          "Hard Boiled",
        ],
      },
    ],
  },
  {
    slug: "science-fiction",
    name: "Science fiction",
    lists: [
      {
        slug: "existential-sci-fi",
        title: "Existential Sci-Fi",
        description: "Science fiction concerned with being human",
        films: [
          "Blade Runner 2049",
          "Her",
          "Ex Machina",
          "Arrival",
          "Solaris",
          "Moon",
          "After Yang",
          "Ghost in the Shell",
        ],
      },
      {
        slug: "what-makes-us-human",
        title: "What Makes Us Human?",
        description: "Consciousness, memory and identity",
        films: [
          "Blade Runner",
          "Blade Runner 2049",
          "Ghost in the Shell",
          "Ex Machina",
          "Her",
          "A.I. Artificial Intelligence",
          "After Yang",
          "Never Let Me Go",
        ],
      },
      {
        slug: "ai-gets-complicated",
        title: "AI Gets Complicated",
        description: "Human relationships with artificial intelligence",
        films: [
          "Her",
          "Ex Machina",
          "A.I. Artificial Intelligence",
          "The Creator",
          "Blade Runner 2049",
          "Upgrade",
          "Archive",
          "I Am Mother",
        ],
      },
      {
        slug: "the-future-is-lonely",
        title: "The Future Is Lonely",
        description: "Technology and isolation",
        films: [
          "Her",
          "Blade Runner 2049",
          "Moon",
          "After Yang",
          "Ad Astra",
          "Solaris",
          "High Life",
          "Gattaca",
        ],
      },
      {
        slug: "reality-is-breaking",
        title: "Reality Is Breaking",
        description: "Reality itself cannot be trusted",
        films: [
          "The Matrix",
          "Coherence",
          "Dark City",
          "Primer",
          "eXistenZ",
          "Donnie Darko",
          "Source Code",
          "The Thirteenth Floor",
        ],
      },
      {
        slug: "first-contact",
        title: "First Contact",
        description: "Encountering intelligence beyond humanity",
        films: [
          "Arrival",
          "Contact",
          "Close Encounters of the Third Kind",
          "Annihilation",
          "Solaris",
          "The Vast of Night",
          "The Day the Earth Stood Still",
          "District 9",
        ],
      },
      {
        slug: "cosmic-loneliness",
        title: "Cosmic Loneliness",
        description: "Isolation against an enormous universe",
        films: [
          "Solaris",
          "Moon",
          "Ad Astra",
          "High Life",
          "Aniara",
          "2001: A Space Odyssey",
          "Gravity",
          "Silent Running",
        ],
      },
    ],
  },
  {
    slug: "comfort-accessible-viewing",
    name: "Comfort & accessible viewing",
    lists: [
      {
        slug: "comfort-cinema",
        title: "Comfort Cinema",
        description: "Warm, familiar and reassuring",
        films: [
          "Paddington 2",
          "Amélie",
          "Chef",
          "About Time",
          "The Intern",
          "Little Women",
          "Sing Street",
          "The Secret Life of Walter Mitty",
        ],
      },
      {
        slug: "life-might-be-okay",
        title: "Life Might Be Okay",
        description: "Gentle films that restore some optimism",
        films: [
          "Perfect Days",
          "Paterson",
          "Chef",
          "The Straight Story",
          "The Holdovers",
          "About Time",
          "Local Hero",
          "The Station Agent",
        ],
      },
      {
        slug: "warm-human-stories",
        title: "Warm Human Stories",
        description: "Character-driven emotional warmth",
        films: [
          "The Holdovers",
          "The Farewell",
          "Little Miss Sunshine",
          "CODA",
          "Minari",
          "The Intouchables",
          "The Lunchbox",
          "The Peanut Butter Falcon",
        ],
      },
      {
        slug: "smart-but-easy",
        title: "Smart but Easy",
        description: "Intelligent entertainment without heavy homework",
        films: [
          "Ocean's Eleven",
          "Knives Out",
          "Moneyball",
          "The Martian",
          "The Big Short",
          "Catch Me If You Can",
          "The Nice Guys",
          "Ford v Ferrari",
        ],
      },
      {
        slug: "sunday-afternoon",
        title: "Sunday Afternoon",
        description: "Relaxed films for an unhurried afternoon",
        films: [
          "Chef",
          "About Time",
          "Julie & Julia",
          "The Intern",
          "Paterson",
          "Midnight in Paris",
          "Little Women",
          "The Lunchbox",
        ],
      },
    ],
  },
];
