/**
 * The starting catalogue.
 *
 * Synopses are written for xine rather than lifted from anywhere, and no
 * poster art is bundled — films seed with `posterUrl: null` and the UI draws
 * a typographic plate instead. Set TMDB_API_KEY and run `npm run films:sync`
 * to attach real artwork and expand the catalogue.
 */

export type SeedFilm = {
  slug: string;
  title: string;
  originalTitle?: string;
  year: number;
  runtime: number;
  director: string;
  country: string;
  language: string;
  genres: string[];
  cast: string[];
  cinematographer?: string;
  composer?: string;
  criticScore: number;
  synopsis: string;
};

export const SEED_FILMS: SeedFilm[] = [
  {
    slug: "dune-part-two",
    title: "Dune: Part Two",
    year: 2024,
    runtime: 166,
    director: "Denis Villeneuve",
    country: "United States",
    language: "English",
    genres: ["Science Fiction", "Epic", "Adventure"],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Austin Butler"],
    cinematographer: "Greig Fraser",
    composer: "Hans Zimmer",
    criticScore: 8.7,
    synopsis:
      "An exiled heir joins the desert people who took him in, and finds that the prophecy welcoming him was planted there generations ago. A war film about how belief gets manufactured, staged at a scale that makes the argument physical.",
  },
  {
    slug: "the-brutalist",
    title: "The Brutalist",
    year: 2024,
    runtime: 215,
    director: "Brady Corbet",
    country: "United States",
    language: "English",
    genres: ["Drama", "Period"],
    cast: ["Adrien Brody", "Felicity Jones", "Guy Pearce"],
    cinematographer: "Lol Crawley",
    composer: "Daniel Blumberg",
    criticScore: 8.6,
    synopsis:
      "A Hungarian architect arrives in postwar America and is handed the commission of his life by a patron who wants ownership as much as a building. Shot on VistaVision, with an intermission, and unembarrassed about its own size.",
  },
  {
    slug: "enemy",
    title: "Enemy",
    year: 2013,
    runtime: 91,
    director: "Denis Villeneuve",
    country: "Canada",
    language: "English",
    genres: ["Psychological Thriller", "Mystery"],
    cast: ["Jake Gyllenhaal", "Mélanie Laurent", "Sarah Gadon"],
    cinematographer: "Nicolas Bolduc",
    criticScore: 7.6,
    synopsis:
      "A lecturer spots a bit-part actor in a rented film who has his exact face, and cannot leave it alone. Jaundiced, airless, and built entirely around a final shot that reorganises everything before it.",
  },
  {
    slug: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: 2017,
    runtime: 164,
    director: "Denis Villeneuve",
    country: "United States",
    language: "English",
    genres: ["Science Fiction", "Noir"],
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks"],
    cinematographer: "Roger Deakins",
    composer: "Hans Zimmer",
    criticScore: 8.4,
    synopsis:
      "A replicant detective pulls a thread in a buried case and finds a question about his own origin waiting at the end of it. The rare sequel that slows a franchise down instead of accelerating it.",
  },
  {
    slug: "the-shining",
    title: "The Shining",
    year: 1980,
    runtime: 146,
    director: "Stanley Kubrick",
    country: "United Kingdom",
    language: "English",
    genres: ["Horror", "Psychological Thriller"],
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
    cinematographer: "John Alcott",
    criticScore: 9.0,
    synopsis:
      "A family takes a winter caretaking job at an empty mountain hotel whose geometry refuses to add up. The horror is architectural before it is ever supernatural.",
  },
  {
    slug: "in-the-mood-for-love",
    title: "In the Mood for Love",
    originalTitle: "花樣年華",
    year: 2000,
    runtime: 98,
    director: "Wong Kar-wai",
    country: "Hong Kong",
    language: "Cantonese",
    genres: ["Romance", "Drama"],
    cast: ["Tony Leung Chiu-wai", "Maggie Cheung"],
    cinematographer: "Christopher Doyle",
    composer: "Michael Galasso",
    criticScore: 9.2,
    synopsis:
      "Two neighbours in 1962 Hong Kong work out that their spouses are having an affair, and construct an elaborate restraint around their own. Everything happens in corridors, stairwells and the space between two people who will not close it.",
  },
  {
    slug: "chungking-express",
    title: "Chungking Express",
    originalTitle: "重慶森林",
    year: 1994,
    runtime: 102,
    director: "Wong Kar-wai",
    country: "Hong Kong",
    language: "Cantonese",
    genres: ["Romance", "Comedy", "Drama"],
    cast: ["Brigitte Lin", "Tony Leung Chiu-wai", "Faye Wong", "Takeshi Kaneshiro"],
    cinematographer: "Christopher Doyle",
    criticScore: 8.8,
    synopsis:
      "Two loosely joined stories about policemen getting over women, shot fast and loose in Hong Kong's crowded middle. Smeared handheld, expiring tins of pineapple, and a song played until it becomes a character.",
  },
  {
    slug: "parasite",
    title: "Parasite",
    originalTitle: "기생충",
    year: 2019,
    runtime: 132,
    director: "Bong Joon-ho",
    country: "South Korea",
    language: "Korean",
    genres: ["Thriller", "Dark Comedy", "Drama"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    cinematographer: "Hong Kyung-pyo",
    composer: "Jung Jae-il",
    criticScore: 9.1,
    synopsis:
      "A family in a semi-basement talks its way into every job in a wealthy household, one referral at a time. A comedy of manners that turns, at a precise midpoint, into something with no exit.",
  },
  {
    slug: "memories-of-murder",
    title: "Memories of Murder",
    originalTitle: "살인의 추억",
    year: 2003,
    runtime: 131,
    director: "Bong Joon-ho",
    country: "South Korea",
    language: "Korean",
    genres: ["Crime", "Drama", "Thriller"],
    cast: ["Song Kang-ho", "Kim Sang-kyung", "Kim Roi-ha"],
    cinematographer: "Kim Hyung-koo",
    criticScore: 8.9,
    synopsis:
      "Two provincial detectives fail, repeatedly and in public, to solve a series of killings in 1980s Korea. A police procedural about the incompetence of a state, ending on a look directly into the camera.",
  },
  {
    slug: "burning",
    title: "Burning",
    originalTitle: "버닝",
    year: 2018,
    runtime: 148,
    director: "Lee Chang-dong",
    country: "South Korea",
    language: "Korean",
    genres: ["Psychological Thriller", "Mystery", "Drama"],
    cast: ["Yoo Ah-in", "Steven Yeun", "Jeon Jong-seo"],
    cinematographer: "Hong Kyung-pyo",
    composer: "Mowg",
    criticScore: 8.7,
    synopsis:
      "A drifting young writer meets a woman from his hometown and the rich, unreadable man she returns with. Class resentment shot as slow-burning ambiguity, where nothing is confirmed and everything is felt.",
  },
  {
    slug: "drive-my-car",
    title: "Drive My Car",
    originalTitle: "ドライブ・マイ・カー",
    year: 2021,
    runtime: 179,
    director: "Ryusuke Hamaguchi",
    country: "Japan",
    language: "Japanese",
    genres: ["Drama"],
    cast: ["Hidetoshi Nishijima", "Tōko Miura", "Reika Kirishima"],
    cinematographer: "Hidetoshi Shinomiya",
    composer: "Eiko Ishibashi",
    criticScore: 8.8,
    synopsis:
      "A widowed theatre director stages a multilingual Uncle Vanya and is assigned a driver he did not want. Three hours of people talking in cars, and one of the great recent films about grief being outrun rather than felt.",
  },
  {
    slug: "perfect-days",
    title: "Perfect Days",
    year: 2023,
    runtime: 124,
    director: "Wim Wenders",
    country: "Japan",
    language: "Japanese",
    genres: ["Drama"],
    cast: ["Kōji Yakusho", "Tokio Emoto", "Arisa Nakano"],
    cinematographer: "Franz Lustig",
    criticScore: 8.3,
    synopsis:
      "A man cleans public toilets in Tokyo, listens to cassettes, photographs trees, and repeats. The repetition is the film, and the small breaks in it land like events.",
  },
  {
    slug: "past-lives",
    title: "Past Lives",
    year: 2023,
    runtime: 105,
    director: "Celine Song",
    country: "United States",
    language: "English",
    genres: ["Romance", "Drama"],
    cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
    cinematographer: "Shabier Kirchner",
    criticScore: 8.6,
    synopsis:
      "Two childhood friends separated by emigration meet again in New York, twenty-four years and one marriage later. A film almost entirely about the version of a life that did not happen.",
  },
  {
    slug: "aftersun",
    title: "Aftersun",
    year: 2022,
    runtime: 102,
    director: "Charlotte Wells",
    country: "United Kingdom",
    language: "English",
    genres: ["Drama"],
    cast: ["Paul Mescal", "Frankie Corio", "Celia Rowlson-Hall"],
    cinematographer: "Gregory Oke",
    composer: "Oliver Coates",
    criticScore: 8.7,
    synopsis:
      "A woman reassembles a package holiday she took with her father at eleven, out of camcorder footage and gaps. What the child could not see is the entire subject.",
  },
  {
    slug: "portrait-of-a-lady-on-fire",
    title: "Portrait of a Lady on Fire",
    originalTitle: "Portrait de la jeune fille en feu",
    year: 2019,
    runtime: 122,
    director: "Céline Sciamma",
    country: "France",
    language: "French",
    genres: ["Romance", "Period", "Drama"],
    cast: ["Noémie Merlant", "Adèle Haenel", "Luàna Bajrami"],
    cinematographer: "Claire Mathon",
    criticScore: 9.0,
    synopsis:
      "A painter is sent to a Breton island to produce a marriage portrait of a woman who refuses to sit for one. A film about looking, made by a camera that never looks at anyone the way a man's would.",
  },
  {
    slug: "anatomy-of-a-fall",
    title: "Anatomy of a Fall",
    originalTitle: "Anatomie d'une chute",
    year: 2023,
    runtime: 152,
    director: "Justine Triet",
    country: "France",
    language: "French",
    genres: ["Courtroom Drama", "Mystery"],
    cast: ["Sandra Hüller", "Swann Arlaud", "Milo Machado-Graner"],
    cinematographer: "Simon Beaufils",
    criticScore: 8.5,
    synopsis:
      "A writer stands trial for her husband's death, with their partially sighted son as the only witness. The trial is really an audit of a marriage, conducted in front of people entitled to an answer the film declines to give.",
  },
  {
    slug: "the-zone-of-interest",
    title: "The Zone of Interest",
    year: 2023,
    runtime: 105,
    director: "Jonathan Glazer",
    country: "United Kingdom",
    language: "German",
    genres: ["Drama", "War", "Historical"],
    cast: ["Christian Friedel", "Sandra Hüller"],
    cinematographer: "Łukasz Żal",
    composer: "Mica Levi",
    criticScore: 8.9,
    synopsis:
      "A commandant's family builds a comfortable domestic life on the other side of a garden wall. The camera stays in the house; the sound design refuses to, and that split is the whole film.",
  },
  {
    slug: "under-the-skin",
    title: "Under the Skin",
    year: 2013,
    runtime: 108,
    director: "Jonathan Glazer",
    country: "United Kingdom",
    language: "English",
    genres: ["Science Fiction", "Horror", "Drama"],
    cast: ["Scarlett Johansson"],
    cinematographer: "Daniel Landin",
    composer: "Mica Levi",
    criticScore: 8.2,
    synopsis:
      "Something wearing a woman's body drives a van around Glasgow collecting men. Hidden-camera documentary footage spliced into pure abstraction, scored by strings that sound like an instrument being harmed.",
  },
  {
    slug: "there-will-be-blood",
    title: "There Will Be Blood",
    year: 2007,
    runtime: 158,
    director: "Paul Thomas Anderson",
    country: "United States",
    language: "English",
    genres: ["Drama", "Period", "Western"],
    cast: ["Daniel Day-Lewis", "Paul Dano", "Dillon Freasier"],
    cinematographer: "Robert Elswit",
    composer: "Jonny Greenwood",
    criticScore: 9.1,
    synopsis:
      "A prospector builds an oil empire in California and a rival pulpit rises to meet him. Fifteen minutes without dialogue to open, and a score that treats the landscape as a threat.",
  },
  {
    slug: "stalker",
    title: "Stalker",
    originalTitle: "Сталкер",
    year: 1979,
    runtime: 162,
    director: "Andrei Tarkovsky",
    country: "Soviet Union",
    language: "Russian",
    genres: ["Science Fiction", "Drama"],
    cast: ["Alexander Kaidanovsky", "Anatoly Solonitsyn", "Nikolai Grinko"],
    cinematographer: "Alexander Knyazhinsky",
    composer: "Eduard Artemyev",
    criticScore: 9.0,
    synopsis:
      "A guide leads a writer and a scientist through a forbidden zone toward a room that grants what you actually want, rather than what you ask for. Almost no incident, and unbearable tension throughout.",
  },
  {
    slug: "mirror",
    title: "Mirror",
    originalTitle: "Зеркало",
    year: 1975,
    runtime: 107,
    director: "Andrei Tarkovsky",
    country: "Soviet Union",
    language: "Russian",
    genres: ["Drama"],
    cast: ["Margarita Terekhova", "Ignat Daniltsev", "Oleg Yankovsky"],
    cinematographer: "Georgy Rerberg",
    composer: "Eduard Artemyev",
    criticScore: 8.8,
    synopsis:
      "Memory, newsreel and dream assembled without a connecting plot, in the order a life actually returns to you. The most literal attempt anyone has made to film the inside of remembering.",
  },
  {
    slug: "uncle-boonmee",
    title: "Uncle Boonmee Who Can Recall His Past Lives",
    originalTitle: "ลุงบุญมีระลึกชาติ",
    year: 2010,
    runtime: 113,
    director: "Apichatpong Weerasethakul",
    country: "Thailand",
    language: "Thai",
    genres: ["Drama", "Fantasy"],
    cast: ["Thanapat Saisaymar", "Jenjira Pongpas", "Sakda Kaewbuadee"],
    cinematographer: "Sayombhu Mukdeeprom",
    criticScore: 8.4,
    synopsis:
      "A dying man is visited in the countryside by his late wife and a son who returned from the forest as something else. Ghosts arrive at dinner and nobody raises their voice.",
  },
  {
    slug: "cemetery-of-splendour",
    title: "Cemetery of Splendour",
    originalTitle: "รักที่ขอนแก่น",
    year: 2015,
    runtime: 122,
    director: "Apichatpong Weerasethakul",
    country: "Thailand",
    language: "Thai",
    genres: ["Drama", "Fantasy"],
    cast: ["Jenjira Pongpas", "Banlop Lomnoi", "Jarinpattra Rueangram"],
    cinematographer: "Diego García",
    criticScore: 8.1,
    synopsis:
      "Soldiers with an unexplained sleeping sickness are treated in a converted school built over a royal graveyard. Politics conducted entirely through the unconscious.",
  },
  {
    slug: "inside-the-yellow-cocoon-shell",
    title: "Inside the Yellow Cocoon Shell",
    originalTitle: "Bên trong vỏ kén vàng",
    year: 2023,
    runtime: 182,
    director: "Phạm Thiên Ân",
    country: "Vietnam",
    language: "Vietnamese",
    genres: ["Drama", "Spiritual"],
    cast: ["Lê Phong Vũ", "Nguyễn Thị Trúc Quỳnh", "Nguyễn Thịnh"],
    cinematographer: "Đinh Duy Hưng",
    criticScore: 8.5,
    synopsis:
      "After a fatal accident in Saigon, a man carries his young nephew back to the highlands to find a brother who disappeared years ago. Three hours of long takes and fog, and a Caméra d'Or that announced a filmmaker fully formed.",
  },
  {
    slug: "the-scent-of-green-papaya",
    title: "The Scent of Green Papaya",
    originalTitle: "Mùi đu đủ xanh",
    year: 1993,
    runtime: 104,
    director: "Trần Anh Hùng",
    country: "Vietnam",
    language: "Vietnamese",
    genres: ["Drama", "Period"],
    cast: ["Trần Nữ Yên Khê", "Lu Man San", "Vuong Hoa Hoi"],
    cinematographer: "Benoît Delhomme",
    composer: "Tôn-Thất Tiết",
    criticScore: 8.2,
    synopsis:
      "A servant girl grows up inside a Saigon household in the 1950s, observed through gestures, insects and light on wet stone. Built entirely on a Paris soundstage, which is exactly why it feels like memory.",
  },
  {
    slug: "cyclo",
    title: "Cyclo",
    originalTitle: "Xích lô",
    year: 1995,
    runtime: 129,
    director: "Trần Anh Hùng",
    country: "Vietnam",
    language: "Vietnamese",
    genres: ["Crime", "Drama"],
    cast: ["Lê Văn Lộc", "Tony Leung Chiu-wai", "Trần Nữ Yên Khê"],
    cinematographer: "Benoît Delhomme",
    composer: "Tôn-Thất Tiết",
    criticScore: 8.0,
    synopsis:
      "A rickshaw driver in Ho Chi Minh City loses his cyclo and is absorbed by the gang that took it. The companion piece to Green Papaya, and its exact inverse in temperament.",
  },
  {
    slug: "song-lang",
    title: "Song Lang",
    year: 2018,
    runtime: 101,
    director: "Leon Le",
    country: "Vietnam",
    language: "Vietnamese",
    genres: ["Drama", "Musical"],
    cast: ["Liên Bỉnh Phát", "Isaac"],
    cinematographer: "Bob Nguyễn",
    criticScore: 7.8,
    synopsis:
      "A debt collector and a cải lương opera singer spend a night in 1980s Saigon that neither expected. Period design and neon doing the emotional work the dialogue withholds.",
  },
  {
    slug: "the-wolf-of-wall-street",
    title: "The Wolf of Wall Street",
    year: 2013,
    runtime: 180,
    director: "Martin Scorsese",
    country: "United States",
    language: "English",
    genres: ["Dark Comedy", "Crime", "Biography"],
    cast: [
      "Leonardo DiCaprio",
      "Jonah Hill",
      "Margot Robbie",
      "Matthew McConaughey",
      "Kyle Chandler",
    ],
    cinematographer: "Rodrigo Prieto",
    criticScore: 9.6,
    synopsis:
      "Jordan Belfort works out that the job was never picking stocks, founds Stratton Oakmont in a Long Island strip mall, and spends three hours proving how far a fast mouth and no conscience will carry you. A comedy about greed that refuses to hand you the moral at the end.",
  },
  {
    slug: "fight-club",
    title: "Fight Club",
    year: 1999,
    runtime: 139,
    director: "David Fincher",
    country: "United States",
    language: "English",
    genres: ["Drama", "Dark Comedy", "Psychological Thriller"],
    cast: [
      "Edward Norton",
      "Brad Pitt",
      "Helena Bonham Carter",
      "Meat Loaf",
      "Jared Leto",
    ],
    cinematographer: "Jeff Cronenweth",
    composer: "The Dust Brothers",
    criticScore: 8.6,
    synopsis:
      "An insomniac office worker with a catalogue habit meets a soap salesman who offers him a way out of everything he owns. Fincher shoots consumer despair like a horror film and lets the joke curdle exactly on schedule.",
  },
  {
    slug: "shutter-island",
    title: "Shutter Island",
    year: 2010,
    runtime: 138,
    director: "Martin Scorsese",
    country: "United States",
    language: "English",
    genres: ["Psychological Thriller", "Mystery", "Period"],
    cast: [
      "Leonardo DiCaprio",
      "Mark Ruffalo",
      "Ben Kingsley",
      "Michelle Williams",
      "Max von Sydow",
    ],
    cinematographer: "Robert Richardson",
    criticScore: 8.1,
    synopsis:
      "Two marshals travel to a hospital for the criminally insane to investigate a patient who has vanished from a locked room. A storm closes the island behind them, and the investigation starts costing one of them more than it should.",
  },
  {
    slug: "the-sixth-sense",
    title: "The Sixth Sense",
    year: 1999,
    runtime: 107,
    director: "M. Night Shyamalan",
    country: "United States",
    language: "English",
    genres: ["Psychological Thriller", "Drama", "Horror"],
    cast: [
      "Bruce Willis",
      "Haley Joel Osment",
      "Toni Collette",
      "Olivia Williams",
    ],
    cinematographer: "Tak Fujimoto",
    composer: "James Newton Howard",
    criticScore: 8.3,
    synopsis:
      "A child psychologist takes on a withdrawn boy carrying a secret he cannot tell anyone. Built almost entirely out of restraint and staging, and quiet enough that the scares land as grief.",
  },
  {
    slug: "the-godfather",
    title: "The Godfather",
    year: 1972,
    runtime: 175,
    director: "Francis Ford Coppola",
    country: "United States",
    language: "English",
    genres: ["Crime", "Drama"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    cinematographer: "Gordon Willis",
    composer: "Nino Rota",
    criticScore: 9.5,
    synopsis:
      "The war-hero son who wanted no part of the family business takes a meeting, and never gets out again. Willis lit it like a Rembrandt and started an argument about underexposure that lasted a decade.",
  },
  {
    slug: "the-godfather-part-ii",
    title: "The Godfather Part II",
    year: 1974,
    runtime: 202,
    director: "Francis Ford Coppola",
    country: "United States",
    language: "English",
    genres: ["Crime", "Drama"],
    cast: ["Al Pacino", "Robert De Niro", "Diane Keaton", "John Cazale"],
    cinematographer: "Gordon Willis",
    composer: "Nino Rota",
    criticScore: 9.4,
    synopsis:
      "A father's rise cut against a son's consolidation, so that every gain in one timeline reads as a loss in the other. Ends on the coldest courtyard in American cinema.",
  },
  {
    slug: "glorious-ashes",
    title: "Glorious Ashes",
    originalTitle: "Tro tàn rực rỡ",
    year: 2022,
    runtime: 116,
    director: "Bùi Thạc Chuyên",
    country: "Vietnam",
    language: "Vietnamese",
    genres: ["Drama"],
    cast: ["Phương Anh Đào", "Juliet Bảo Ngọc Doling", "Lê Công Hoàng"],
    cinematographer: "Nguyễn K'Linh",
    criticScore: 7.9,
    synopsis:
      "Three women in a Mekong Delta fishing village, bound to men who burn things down. Adapted from Nguyễn Ngọc Tư, and the strongest Vietnamese festival film of its year.",
  },
];
